name: orders-tests

on:
  pull_request:
    paths:
      - 'orders/**'
      - '.github/workflows/orders-tests.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
